// !!!! DO NOT EDIT !!!, use: make config

#ifndef _CONFIG_H_
#define _CONFIG_H_

// CONFIG_DEBUG is not set
// USE_LCD_CHARGE_PUMP is not set
#define USE_WATCHDOG
#define CONFIG_RTC_IRQ
// CONFIG_RTC_DST is not set
#define CONFIG_RTC_DST_ZONE 4
#define CONFIG_TIMER_4S_IRQ
#define CONFIG_TIMER_20HZ_IRQ
#ifndef CONFIG_BUTTONS_LONG_PRESS_TIME
#define CONFIG_BUTTONS_LONG_PRESS_TIME 15
#endif // CONFIG_BUTTONS_LONG_PRESS_TIME
#ifndef CONFIG_BUTTONS_SHORT_PRESS_TIME
#define CONFIG_BUTTONS_SHORT_PRESS_TIME 2
#endif // CONFIG_BUTTONS_SHORT_PRESS_TIME
#define CONFIG_BATTERY_MONITOR
#define CONFIG_BATTERY_DISABLE_FILTER
#ifndef CONFIG_TEMPERATURE_OFFSET
#define CONFIG_TEMPERATURE_OFFSET -260
#endif // CONFIG_TEMPERATURE_OFFSET
#define CONFIG_TEMPERATURE_METRIC
#define CONFIG_MOD_ALARM
#define CONFIG_MOD_RPC
#define CONFIG_MOD_RESET
#define CONFIG_MOD_BATTERY
#define CONFIG_MOD_BATTERY_SHOW_VOLTAGE
#define CONFIG_MOD_STOPWATCH
#define CONFIG_MOD_CLOCK
#define CONFIG_MOD_CLOCK_BLINKCOL
// CONFIG_MOD_CLOCK_AMPM is not set
// CONFIG_MOD_CLOCK_MONTH_FIRST is not set

#define CONFIG_DEBUG

#endif // _CONFIG_H_
